app.controller('indexContentService',function($scope,indexContentCatService){
    $scope.ContentCateglist=[{'luenbo':{}}];
    //查询首页轮播广告
    $scope.ContentCategoryList=function(id){
        indexContentCatService.ContentCatList(id).success(function(response){
            $scope.ContentCateglist.luenbo=response;
        })
    }
    //搜索页面跳转
        $scope.search=function(){
            window.location.href="http://localhost:9104/search.html#?name="+$scope.name;
        }
})